// <auto-generated />
using CutItUp.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CutItUp.Data.Migrations
{
    [DbContext(typeof(CutItUpContext))]
    partial class CutItUpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CutItUp.Data.Data.Abstractions.Tool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Dimension")
                        .HasColumnType("real");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Length")
                        .HasColumnType("real");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoOfSaled")
                        .HasColumnType("int");

                    b.Property<int>("NoOfToolsInMagazine")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Tool");

                    b.HasDiscriminator().HasValue("Tool");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CutItUp.Data.Data.CMS.GPT.GPTMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsUsersMesssage")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GPTMessage");
                });

            modelBuilder.Entity("CutItUp.Data.Data.CMS.ListPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListContentSerialized")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WebsiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WebsiteId");

                    b.ToTable("ListPart");
                });

            modelBuilder.Entity("CutItUp.Data.Data.CMS.MainWebsite.Promo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromoFileURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Promo");
                });

            modelBuilder.Entity("CutItUp.Data.Data.CMS.MainWebsite.WhyUsSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("Reasons")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WhyUsSection");
                });

            modelBuilder.Entity("CutItUp.Data.Data.CMS.TitleDescriptionPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WebsiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WebsiteId");

                    b.ToTable("TitleDescriptionPart");
                });

            modelBuilder.Entity("CutItUp.Data.Data.CMS.Website", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Website");
                });

            modelBuilder.Entity("CutItUp.Data.Data.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("CutItUp.Data.Data.CartTool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ToolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ToolId");

                    b.ToTable("CartTool");
                });

            modelBuilder.Entity("CutItUp.Data.Data.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CutItUp.Data.Data.Tools.Drill", b =>
                {
                    b.HasBaseType("CutItUp.Data.Data.Abstractions.Tool");

                    b.Property<float>("Angle")
                        .HasColumnType("real");

                    b.HasDiscriminator().HasValue("Drill");
                });

            modelBuilder.Entity("CutItUp.Data.Data.Tools.Mill", b =>
                {
                    b.HasBaseType("CutItUp.Data.Data.Abstractions.Tool");

                    b.Property<int>("NoCuttingEddges")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Mill");
                });

            modelBuilder.Entity("CutItUp.Data.Data.Tools.SpecialTool", b =>
                {
                    b.HasBaseType("CutItUp.Data.Data.Abstractions.Tool");

                    b.Property<float?>("Angle")
                        .HasColumnType("real");

                    b.Property<int>("NoCuttingEddges")
                        .HasColumnType("int");

                    b.Property<float?>("Radius")
                        .HasColumnType("real");

                    b.ToTable("Tool", t =>
                        {
                            t.Property("Angle")
                                .HasColumnName("SpecialTool_Angle");

                            t.Property("NoCuttingEddges")
                                .HasColumnName("SpecialTool_NoCuttingEddges");
                        });

                    b.HasDiscriminator().HasValue("SpecialTool");
                });

            modelBuilder.Entity("CutItUp.Data.Data.Tools.Tap", b =>
                {
                    b.HasBaseType("CutItUp.Data.Data.Abstractions.Tool");

                    b.Property<bool>("PassThrough")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Tap");
                });

            modelBuilder.Entity("CutItUp.Data.Data.CMS.ListPart", b =>
                {
                    b.HasOne("CutItUp.Data.Data.CMS.Website", "Website")
                        .WithMany("ListParts")
                        .HasForeignKey("WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Website");
                });

            modelBuilder.Entity("CutItUp.Data.Data.CMS.TitleDescriptionPart", b =>
                {
                    b.HasOne("CutItUp.Data.Data.CMS.Website", "Website")
                        .WithMany("TitleDecriptionParts")
                        .HasForeignKey("WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Website");
                });

            modelBuilder.Entity("CutItUp.Data.Data.CartTool", b =>
                {
                    b.HasOne("CutItUp.Data.Data.Cart", "Cart")
                        .WithMany("Tools")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CutItUp.Data.Data.Abstractions.Tool", "Tool")
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("CutItUp.Data.Data.CMS.Website", b =>
                {
                    b.Navigation("ListParts");

                    b.Navigation("TitleDecriptionParts");
                });

            modelBuilder.Entity("CutItUp.Data.Data.Cart", b =>
                {
                    b.Navigation("Tools");
                });
#pragma warning restore 612, 618
        }
    }
}
